elasticsearch:
    image: elasticsearch:latest

augur_node:
    build: .
    command: sh /home/augur/start.sh
    volumes:
        - .:/home/augur
        - /home/augur/node_modules
    ports:
        - '8547:8547'
    links:
        - elasticsearch
