elasticsearch:
    image: elasticsearch:latest

geth:
    image: ethereum/client-go:alpine
    entrypoint: sh /root/start_geth.sh
    volumes:
       - ./:/root
    #ports:
    #    - '8545:8545'
    #    - '8546:8546'

augur_node:
    build: .
    command: sh /home/augur/start_augur_node.sh
    volumes:
        - .:/home/augur
        - /home/augur/node_modules
    ports:
        - '8547:8547'
    links:
        - elasticsearch
        - geth
